- name : Configure Docker on EC2 Instances
  hosts : Productionservers
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : apt-get update

  - name : Install Docker
    command : apt-get install -y docker.io

  - name : Start Docker Service
    command : systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8080:8081 dilipdil/docker-pipeline
