- name: Configure Docker on EC2 Instances
  hosts: Productionservers
  become: true
  connection: ssh
  tasks:
    - name: updating apt
      command: sudo apt-get update

    - name: Update package lists and upgrade packages
      command: sudo apt-get update && sudo apt-get upgrade -y

    - name: Install Docker dependencies
      command: sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

    - name: Install Docker and containerd
      command: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo apt-get install -y containerd

    - name: Start Docker Service
      command: sudo systemctl start docker

    - name: Deploy Docker Container
      command: docker run -itd -p 8080:8081 dilipdil/docker-pipeline

